// <auto-generated />
using System;
using CSMPMWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSMPMWeb.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20190725075212_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CSMPMLib.Crop", b =>
                {
                    b.Property<int>("CropId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CropGroupId");

                    b.Property<string>("CropName");

                    b.Property<double>("IrrigationRate");

                    b.Property<double>("WateringRate");

                    b.HasKey("CropId");

                    b.HasIndex("CropGroupId");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("CSMPMLib.CropGroup", b =>
                {
                    b.Property<int>("CropGroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CropGroupName");

                    b.HasKey("CropGroupId");

                    b.ToTable("CropGroups");
                });

            modelBuilder.Entity("CSMPMLib.IrrigationCanal", b =>
                {
                    b.Property<int>("IrrigationCanalId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IrrigationCanalName");

                    b.Property<int>("IrrigationGridId");

                    b.HasKey("IrrigationCanalId");

                    b.HasIndex("IrrigationGridId");

                    b.ToTable("IrrigationCanals");
                });

            modelBuilder.Entity("CSMPMLib.IrrigationCanalConnectionPoint", b =>
                {
                    b.Property<int>("IrrigationCanalConnectionPointId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IrrigationCanalConnectionPointName");

                    b.HasKey("IrrigationCanalConnectionPointId");

                    b.ToTable("IrrigationCanalConnectionPoints");
                });

            modelBuilder.Entity("CSMPMLib.IrrigationCanalConnectionPointToIrrigationCanal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IrrigationCanalConnectionPointId");

                    b.Property<int>("IrrigationCanalConnectionPointTypeId");

                    b.Property<int>("IrrigationCanalId");

                    b.HasKey("Id");

                    b.HasIndex("IrrigationCanalConnectionPointId");

                    b.HasIndex("IrrigationCanalConnectionPointTypeId")
                        .HasName("IX_IrrigationCanalConnectionPointToIrrigationCanals_Irrigation~1");

                    b.HasIndex("IrrigationCanalId")
                        .HasName("IX_IrrigationCanalConnectionPointToIrrigationCanals_Irrigation~2");

                    b.ToTable("IrrigationCanalConnectionPointToIrrigationCanals");
                });

            modelBuilder.Entity("CSMPMLib.IrrigationCanalConnectionPointType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("IrrigationCanalConnectionPointTypes");
                });

            modelBuilder.Entity("CSMPMLib.IrrigationGrid", b =>
                {
                    b.Property<int>("IrrigationGridId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IrrigationGridName");

                    b.Property<int>("IrrigationSystemId");

                    b.HasKey("IrrigationGridId");

                    b.HasIndex("IrrigationSystemId");

                    b.ToTable("IrrigationGrids");
                });

            modelBuilder.Entity("CSMPMLib.IrrigationPlan", b =>
                {
                    b.Property<int>("IrrigationPlanId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("OrganizationDocumentationPlansId");

                    b.Property<int>("Year");

                    b.HasKey("IrrigationPlanId");

                    b.HasIndex("OrganizationDocumentationPlansId");

                    b.ToTable("IrrigationPlans");
                });

            modelBuilder.Entity("CSMPMLib.IrrigationPlanItem", b =>
                {
                    b.Property<int>("IrrigationPlanItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IrrigationPlanId");

                    b.Property<string>("IrrigationSystemName");

                    b.Property<double>("LandAreaAgriculturalUse");

                    b.Property<double>("LandAreaIncludedInIrrigationPlan");

                    b.Property<double>("LandAreaOnBeginningOfYear");

                    b.Property<double>("LandAreaSowing");

                    b.HasKey("IrrigationPlanItemId");

                    b.HasIndex("IrrigationPlanId");

                    b.ToTable("IrrigationPlanItems");
                });

            modelBuilder.Entity("CSMPMLib.IrrigationPlanItem_CropSowingAndIrrigation", b =>
                {
                    b.Property<int>("IrrigationPlanItem_CropSowingAndIrrigationId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CropId");

                    b.Property<double>("Irrigation");

                    b.Property<int>("IrrigationPlanItemId");

                    b.Property<double>("Sowing");

                    b.HasKey("IrrigationPlanItem_CropSowingAndIrrigationId");

                    b.HasIndex("CropId");

                    b.HasIndex("IrrigationPlanItemId");

                    b.ToTable("IrrigationPlanItem_CropSowingAndIrrigations");
                });

            modelBuilder.Entity("CSMPMLib.IrrigationPlanItem_LandAreaNotAgriculturalReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Area");

                    b.Property<int?>("IrrigationPlanItemId");

                    b.Property<int>("ReasonId");

                    b.HasKey("Id");

                    b.HasIndex("IrrigationPlanItemId");

                    b.HasIndex("ReasonId");

                    b.ToTable("IrrigationPlanItem_LandAreaNotAgriculturalReasons");
                });

            modelBuilder.Entity("CSMPMLib.IrrigationPlanItem_LandAreaNotIrrigationReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Area");

                    b.Property<int?>("IrrigationPlanItemId");

                    b.Property<int>("ReasonId");

                    b.HasKey("Id");

                    b.HasIndex("IrrigationPlanItemId");

                    b.HasIndex("ReasonId");

                    b.ToTable("IrrigationPlanItem_LandAreaNotIrrigationReasons");
                });

            modelBuilder.Entity("CSMPMLib.IrrigationSystem", b =>
                {
                    b.Property<int>("IrrigationSystemId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IrrigationSystemName");

                    b.HasKey("IrrigationSystemId");

                    b.ToTable("IrrigationSystems");
                });

            modelBuilder.Entity("CSMPMLib.Organization", b =>
                {
                    b.Property<int>("OrganizationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OrganizationName");

                    b.Property<int?>("ParentOrganizationId");

                    b.HasKey("OrganizationId");

                    b.HasIndex("ParentOrganizationId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("CSMPMLib.OrganizationDocumentationItem", b =>
                {
                    b.Property<int>("OrganizationDocumentationItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OrganizationDocumentationItemName");

                    b.Property<int>("OrganizationId");

                    b.HasKey("OrganizationDocumentationItemId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("OrganizationDocumentation");
                });

            modelBuilder.Entity("CSMPMLib.OrganizationDocumentationPlans", b =>
                {
                    b.Property<int>("OrganizationDocumentationPlansId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("OrganizationDocumentationId");

                    b.Property<string>("OrganizationDocumentationPlansName");

                    b.HasKey("OrganizationDocumentationPlansId");

                    b.HasIndex("OrganizationDocumentationId");

                    b.ToTable("OrganizationDocumentationPlans");
                });

            modelBuilder.Entity("CSMPMLib.OrganizationToIrrigationSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IrrigationSystemId");

                    b.Property<int>("OrganizationId");

                    b.Property<int>("OrganizationToSystemRelationTypeId");

                    b.HasKey("Id");

                    b.HasIndex("IrrigationSystemId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationToSystemRelationTypeId");

                    b.ToTable("OrganizationToIrrigationSystems");
                });

            modelBuilder.Entity("CSMPMLib.OrganizationToSystemRelationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("OrganizationToSystemRelationTypes");
                });

            modelBuilder.Entity("CSMPMLib.OrganizationToTypeOfActivity", b =>
                {
                    b.Property<int>("OrganizationToTypeOfActivityId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("OrganizationId");

                    b.Property<int>("TypeOfActivityId");

                    b.HasKey("OrganizationToTypeOfActivityId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("TypeOfActivityId");

                    b.ToTable("OrganizationToTypeOfActivities");
                });

            modelBuilder.Entity("CSMPMLib.Reason", b =>
                {
                    b.Property<int>("ReasonId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ReasonName");

                    b.HasKey("ReasonId");

                    b.ToTable("Reasons");
                });

            modelBuilder.Entity("CSMPMLib.TypeOfActivity", b =>
                {
                    b.Property<int>("TypeOfActivityId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("RootTypeOfActivityId");

                    b.Property<string>("TypeOfActivityName");

                    b.HasKey("TypeOfActivityId");

                    b.HasIndex("RootTypeOfActivityId");

                    b.ToTable("TypeOfActivities");
                });

            modelBuilder.Entity("CSMPMWeb.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("Patronymic");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("CSMPMWeb.Models.AppUserToOrganization", b =>
                {
                    b.Property<int>("AppUserToOrganizationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppUserId");

                    b.Property<int>("OrganizationId");

                    b.HasKey("AppUserToOrganizationId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("AppUserToOrganizations");
                });

            modelBuilder.Entity("CSMPMWeb.Models.AssignedPermission", b =>
                {
                    b.Property<int>("AssignedPermissionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AppUserToOrganizationId");

                    b.Property<int>("SystemModuleId");

                    b.Property<int>("SystemRoleId");

                    b.HasKey("AssignedPermissionId");

                    b.HasIndex("AppUserToOrganizationId");

                    b.HasIndex("SystemModuleId");

                    b.HasIndex("SystemRoleId");

                    b.ToTable("AssignedPermissions");
                });

            modelBuilder.Entity("CSMPMWeb.Models.SystemModule", b =>
                {
                    b.Property<int>("SystemModuleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SystemModuleName");

                    b.HasKey("SystemModuleId");

                    b.ToTable("SystemModules");
                });

            modelBuilder.Entity("CSMPMWeb.Models.SystemRole", b =>
                {
                    b.Property<int>("SystemRoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SystemRoleName");

                    b.HasKey("SystemRoleId");

                    b.ToTable("SystemRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("CSMPMLib.Crop", b =>
                {
                    b.HasOne("CSMPMLib.CropGroup", "CropGroup")
                        .WithMany("Crops")
                        .HasForeignKey("CropGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CSMPMLib.IrrigationCanal", b =>
                {
                    b.HasOne("CSMPMLib.IrrigationGrid", "IrrigationGrid")
                        .WithMany("IrrigationCanals")
                        .HasForeignKey("IrrigationGridId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CSMPMLib.IrrigationCanalConnectionPointToIrrigationCanal", b =>
                {
                    b.HasOne("CSMPMLib.IrrigationCanalConnectionPoint", "IrrigationCanalConnectionPoint")
                        .WithMany("IrrigationCanalConnectionPointToIrrigationCanal")
                        .HasForeignKey("IrrigationCanalConnectionPointId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CSMPMLib.IrrigationCanalConnectionPointType", "IrrigationCanalConnectionPointType")
                        .WithMany()
                        .HasForeignKey("IrrigationCanalConnectionPointTypeId")
                        .HasConstraintName("FK_IrrigationCanalConnectionPointToIrrigationCanals_Irrigation~1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CSMPMLib.IrrigationCanal", "IrrigationCanal")
                        .WithMany()
                        .HasForeignKey("IrrigationCanalId")
                        .HasConstraintName("FK_IrrigationCanalConnectionPointToIrrigationCanals_Irrigation~2")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CSMPMLib.IrrigationGrid", b =>
                {
                    b.HasOne("CSMPMLib.IrrigationSystem", "IrrigationSystem")
                        .WithMany("IrrigationGrids")
                        .HasForeignKey("IrrigationSystemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CSMPMLib.IrrigationPlan", b =>
                {
                    b.HasOne("CSMPMLib.OrganizationDocumentationPlans", "OrganizationDocumentationPlans")
                        .WithMany("IrrigationPlans")
                        .HasForeignKey("OrganizationDocumentationPlansId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CSMPMLib.IrrigationPlanItem", b =>
                {
                    b.HasOne("CSMPMLib.IrrigationPlan", "IrrigationPlan")
                        .WithMany("IrrigationPlanItems")
                        .HasForeignKey("IrrigationPlanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CSMPMLib.IrrigationPlanItem_CropSowingAndIrrigation", b =>
                {
                    b.HasOne("CSMPMLib.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CSMPMLib.IrrigationPlanItem", "IrrigationPlanItem")
                        .WithMany("IrrigationPlanItem_CropSowingAndIrrigations")
                        .HasForeignKey("IrrigationPlanItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CSMPMLib.IrrigationPlanItem_LandAreaNotAgriculturalReason", b =>
                {
                    b.HasOne("CSMPMLib.IrrigationPlanItem")
                        .WithMany("IrrigationPlanItem_LandAreaNotAgriculturalReasons")
                        .HasForeignKey("IrrigationPlanItemId");

                    b.HasOne("CSMPMLib.Reason", "Reason")
                        .WithMany()
                        .HasForeignKey("ReasonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CSMPMLib.IrrigationPlanItem_LandAreaNotIrrigationReason", b =>
                {
                    b.HasOne("CSMPMLib.IrrigationPlanItem")
                        .WithMany("IrrigationPlanItem_LandAreaNotIrrigationReasons")
                        .HasForeignKey("IrrigationPlanItemId");

                    b.HasOne("CSMPMLib.Reason", "Reason")
                        .WithMany()
                        .HasForeignKey("ReasonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CSMPMLib.Organization", b =>
                {
                    b.HasOne("CSMPMLib.Organization", "ParentOrganization")
                        .WithMany("ChildOrganizations")
                        .HasForeignKey("ParentOrganizationId");
                });

            modelBuilder.Entity("CSMPMLib.OrganizationDocumentationItem", b =>
                {
                    b.HasOne("CSMPMLib.Organization", "Organization")
                        .WithMany("OrganizationDocumentation")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CSMPMLib.OrganizationDocumentationPlans", b =>
                {
                    b.HasOne("CSMPMLib.OrganizationDocumentationItem", "OrganizationDocumentation")
                        .WithMany("OrganizationDocumentationPlans")
                        .HasForeignKey("OrganizationDocumentationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CSMPMLib.OrganizationToIrrigationSystem", b =>
                {
                    b.HasOne("CSMPMLib.IrrigationSystem", "IrrigationSystem")
                        .WithMany("OrganizationToIrrigationSystem")
                        .HasForeignKey("IrrigationSystemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CSMPMLib.Organization", "Organization")
                        .WithMany("OrganizationToIrrigationSystem")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CSMPMLib.OrganizationToSystemRelationType", "OrganizationToSystemRelationType")
                        .WithMany()
                        .HasForeignKey("OrganizationToSystemRelationTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CSMPMLib.OrganizationToTypeOfActivity", b =>
                {
                    b.HasOne("CSMPMLib.Organization", "Organization")
                        .WithMany("OrganizationToTypeOfActivities")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CSMPMLib.TypeOfActivity", "TypeOfActivity")
                        .WithMany()
                        .HasForeignKey("TypeOfActivityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CSMPMLib.TypeOfActivity", b =>
                {
                    b.HasOne("CSMPMLib.TypeOfActivity", "RootTypeOfActivity")
                        .WithMany("ChildTypeOfActivities")
                        .HasForeignKey("RootTypeOfActivityId");
                });

            modelBuilder.Entity("CSMPMWeb.Models.AppUserToOrganization", b =>
                {
                    b.HasOne("CSMPMWeb.Models.AppUser", "AppUser")
                        .WithMany("AppUserToOrganizationWithAppUserPermissions")
                        .HasForeignKey("AppUserId");

                    b.HasOne("CSMPMLib.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CSMPMWeb.Models.AssignedPermission", b =>
                {
                    b.HasOne("CSMPMWeb.Models.AppUserToOrganization", "AppUserToOrganization")
                        .WithMany("AssignedPermissions")
                        .HasForeignKey("AppUserToOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CSMPMWeb.Models.SystemModule", "SystemModule")
                        .WithMany("AssignedPermissions")
                        .HasForeignKey("SystemModuleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CSMPMWeb.Models.SystemRole", "SystemRole")
                        .WithMany("AssignedPermissions")
                        .HasForeignKey("SystemRoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CSMPMWeb.Models.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CSMPMWeb.Models.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CSMPMWeb.Models.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CSMPMWeb.Models.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
